const body = document.getElementById('body');

const h1 = document.createElement('h1');
	  h1.innerHTML="Heading generated by JS";
	  
body.appendChild(h1);
	  
const table=  document.createElement('table');
table.setAttribute("border", "1px");
table.setAttribute("width", "500px");

/*********************Table Header Row**************************/

const headerRow =  document.createElement('tr');

const headerCol1=  document.createElement('th');
headerCol1.innerHTML="NAME";

const headerCol2=  document.createElement('th');
headerCol2.innerHTML="AGE";

const headerCol3=  document.createElement('th');
headerCol3.innerHTML="SALARY";

headerRow.appendChild(headerCol1);
headerRow.appendChild(headerCol2);
headerRow.appendChild(headerCol3);

table.appendChild(headerRow);

/*********************Table Data Row**************************/
const dataRow =  document.createElement('tr');

const dataCol1=  document.createElement('td');
dataCol1.innerHTML="Shadab";

const dataCol2=  document.createElement('td');
dataCol2.innerHTML="30";

const dataCol3=  document.createElement('td');
dataCol3.innerHTML="1200";

dataRow.appendChild(dataCol1);
dataRow.appendChild(dataCol2);
dataRow.appendChild(dataCol3);

table.appendChild(dataRow);

body.appendChild(table);